### ISSUE TITLE
No maps

### ISSUE THREAD

**Issue by nicodium** [TeamViscott/ModProjectViscott#3]
Whoever’s responsible for maps should start working on maps man… oh right

**Comment by kapzduke** [comment]
nice small issue. one opinion. no one is working on maps

**Comment by siede2010** [comment]
ethanol has made a map. also made a maps channel in discord nicodium

**Comment by nicodium** [comment]
I know but like after doing maps where do I put them in the mod

**Comment by siede2010** [comment]
Well. we have 1 Test map by now so ima close it for now.
